project:
  type: website
  output-dir: docs

website:
  title: "Tumbleweed"
  navbar:
    pinned: true
    left:
      - text: R
        menu:
          - R/introduccion.qmd
      - text: RNA-seq
        menu:
          - rnaseq/deseq/introduccion.qmd
          - rnaseq/deseq/ejemplo.qmd
      - text: Enriquecimiento funcional
        menu:
          - enrfun/introduccion.qmd
      - text: Presentaciones
        menu:
          - Taller/usaR/usaR.qmd
          - Taller/ggplot2/ggplot2.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    number-sections: false
    highlight-style: dracula
    df-print: kable 



