project:
  type: website
  output-dir: docs

website:
  title: "Tumbleweed"
  navbar:
    pinned: true
    left:
      - text: R
        menu:
          - R/introduccion.qmd
          - R/vectores.qmd
          - R/listas.qmd
          - R/dataframes.qmd
      - text: RNA-seq
        menu:
          - rnaseq/deseq/introduccion.qmd
          - rnaseq/deseq/ejemplo.qmd
      - text: Enriquecimiento funcional
        menu:
          - enrfun/introduccion.qmd
          - enrfun/ora.qmd
          - enrfun/gprofiler.qmd
          - enrfun/gsea.qmd
      - text: Herramientas
        menu:
          - tools/ensembl.qmd
          - tools/geoquery.qmd
      - text: Presentaciones
        menu:
          - presentaciones/usaR/usaR.qmd
          - presentaciones/ggplot2/ggplot2.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    number-sections: false
    highlight-style: dracula
    df-print: kable 



