project:
  type: website

website:
  title: "Tumbleweed"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: RNA-seq
        menu:
          - rnaseq/deseq/introduccion.qmd
          - rnaseq/deseq/ejemplo.qmd
      - about.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true
    number-sections: true
    df-print: kable 



