project:
  type: website

website:
  title: "Tumbleweed"
  navbar:
    pinned: true
    left:
      - text: RNA-seq
        menu:
          - rnaseq/deseq/introduccion.qmd
          - rnaseq/deseq/ejemplo.qmd
      - text: Enriquecimiento funcional
        menu:
          - enrfun/introduccion.qmd
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    number-sections: true
    highlight-style: dracula
    df-print: kable 



