---
title: "Introducción a R"
format: 
    html:
     number-sections: false
---

## ¿Qué es "Programar"?

Programar es el proceso de crear un conjunto de instrucciones para decirle a la computadora cómo realizar una tarea. La tarea de “programar” no se centra exclusivamente en escribir código, si no que conlleva una serie de pasos previos antes de “codificar” las instrucciones.

-   Descomponer un problema complejo en partes más pequeñas.
-   Reconocimiento de patrones repetitivos.
-   Resolución de los problemas paso a paso.
-   Escribir el código.

## ¿Qué es un lenguaje de programación?

Un lenguaje de programación es un lenguaje formal (es decir, un lenguaje con reglas gramaticales bien definidas) que proporciona al programador la capacidad y habilidad de escribir instrucciones o secuencias de órdenes para controlar el comportamiento de un sistema informático.

## El entorno de R

R es un conjunto integrado de software para la manipulación, cálculo y visualización de datos. Entre otras cosas tiene:

-   Tratamiento y almacenamiento de datos eficaz.
-   Conjunto de operadores para el calculo sobre matrices.
-   Conjunto integrado de herramientas para el análisis y visualización de datos.
-   Un simple y efectivo lenguaje de programación.
-   Ampliamente utilizado en investigación cientifica.

## ¿Qué es un "Programa"?

Un programa informático es una secuencia de instrucciones basadas en un lenguaje de programación que el ordenador interpreta para resolver un problema. Los elementos básicos de un programa son:

-   **Instrucciones:** conjunto de ordenes que indican al ordenador como realizar una tarea específica (asignar un valor a una variable, ejecutar un bucle que itera sobre una lista de datos).
-   **Datos:** pueden ser números, texto, imagénes, etc.. . En resumen cualquier tipo de información que el programa manipule. En general, son la razon de ser de muchas aplicaciones.
-   **Operadores:** son las herramientas que permiten realizar operaciones sobre los datos (sumar, multiplicar, comparar, asignar, etc..).
-   **Variables:** actuan como contenedores de información permitiendo que un programa conserve información y realice operaciones sobre esta información, en cierto modo se puede decir que son la “memoria” del programa.

## ¿Qué es un IDE?

Un entorno de desarrollo integrado (IDE) es una aplicación de software que ayuda a los programadores a desarrollar código de software de manera eficiente y aumentando la productividad.

El IDE más popular para R es RStudio, aunque hay otros que tambien se pueden utilizar:

- [RStudio Desktop](https://posit.co/download/rstudio-desktop/)
- [Project Jupyter](https://jupyter.org/)
- [Visual Stuido Code](https://code.visualstudio.com/)
- [Positron](https://github.com/posit-dev/positron)

## ¡Hola Mundo!
El programa "¡Hola Mundo!" suele ser el primer ejercicio típico en la introducción del estudio de un lenguaje de programación.

```{r}
#| label: hola-mundo

saludo <- '¡Hola Mundo!'

saludo
```
En la primera linea el texto *'¡Hola Mundo!'* se asigna a la variable *saludo* usando el operador de asignación *<-* (es posible usar *=*, que es el operador usado en otros lenguajes de programación). En la segunda linea llamamos a la variable *saludo* y se muestra su contenido.

## Variables
Las variables sirven para almacenar un valor (datos, información) que luego vamos a utilizar en algun procedimiento. En general partiremos de unos datos experimentales con los que haremos calculos o otros procedimientos teniendo como resultados datos intermedios. Para poder hacer referencia en R a esos datos, usaremos variables. En R existen varios tipos de objetos que permiten que el usuario pueda almacenar la información para realizar los procedimientos estadísticos y gráficos. En general podemos clasificar las variables en función del tipo de dato que van a almacenar. Así, tendremos variables simples (una variable que almacene el valor 10) o variables más complejas (una variable que almacene la tabla de resultados de un HPLC-MS).

### Variables simples
| Tipo de dato | Descripción                        | Definición           |
|--------------|------------------------------------|----------------------|
| Numeric      | Números decimales                  | numero \<- 1.0       |
| Integer      | Números enteros                    | entero \<- 1         |
| Character    | Cadenas de texto                   | texto \<- "un texto" |
| Complex      | Números complejos                  | complejo \<- 3 + 2i  |
| Logical      | TRUE o FALSE                       | 5 \< 6; 5 == 5       |
| Factor       | Es una variable de tipo categórica |                      |